name: todo
description: A new Flutter project.
version: 1.0.0+1
environment:
  sdk: ">=2.1.0 <3.0.0"
dependencies:
  path_provider: ^1.4.5
  hive: ^1.1.1
  flutter_mobx: ^0.3.3+3
  mobx: ^0.3.9+3
  dio: ^3.0.7
  rxdart: ^0.22.6
  bloc_pattern: ^2.5.1
  flutter:
    sdk: flutter
dev_dependencies:
  mobx_codegen: ^0.3.10+1
  build_runner: ^1.7.1
  mockito: ^4.1.1
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
scripts:
  build: flutter pub run build_runner build
  clean: flutter pub run build_runner clean